import { env } from "../config/env.js";
import { logEvent } from "../lib/logger.js";

export interface ReasoningInput {
  vaultAddress: string;
  riskProfile: string;
  totalPortfolioValue: string;
  currentAllocation: Array<{
    asset: string;
    symbol: string;
    currentWeightPct: number;
    targetWeightPct: number;
    apyBps: number;
    venueLabel: string;
  }>;
  proposedTargets: Array<{
    assetKey: string;
    adapterKey: string;
    weightBps: number;
  }>;
  driftBps: number;
}

export interface ReasoningOutput {
  text: string;
  confidence: number;
  payload: ReasoningInput & { model: string; timestamp: number };
}

export async function generateReasoning(input: ReasoningInput): Promise<ReasoningOutput> {
  if (!env.OPENROUTER_API_KEY) {
    return buildFallback(input, "deterministic");
  }

  try {
    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${env.OPENROUTER_API_KEY}`,
        "HTTP-Referer": "https://equinox.app",
        "X-Title": "Equinox RWA Agent",
      },
      body: JSON.stringify({
        model: env.OPENROUTER_MODEL,
        messages: [
          {
            role: "system",
            content:
              "You are an autonomous portfolio management agent for Equinox RWA, a DeFi yield optimization platform on Mantle. Provide concise, professional reasoning for portfolio rebalancing decisions. Be factual and data-driven. Keep responses under 180 words.",
          },
          { role: "user", content: buildPrompt(input) },
        ],
        max_tokens: 256,
        temperature: 0.3,
      }),
    });

    if (!response.ok) {
      logEvent("warn", "reasoning_openrouter_error", { status: response.status });
      return buildFallback(input, "fallback");
    }

    const data = (await response.json()) as {
      choices: Array<{ message: { content: string } }>;
      model: string;
    };

    const text = data.choices[0]?.message?.content?.trim() ?? buildFallbackText(input);
    return {
      text,
      confidence: 85,
      payload: { ...input, model: data.model ?? env.OPENROUTER_MODEL, timestamp: Date.now() },
    };
  } catch (error) {
    logEvent("warn", "reasoning_fetch_error", { error: String(error) });
    return buildFallback(input, "fallback");
  }
}

function buildPrompt(input: ReasoningInput): string {
  const lines = input.currentAllocation
    .map(
      (a) =>
        `  - ${a.symbol}: current ${a.currentWeightPct.toFixed(1)}% → target ${a.targetWeightPct.toFixed(1)}% | APY ${(a.apyBps / 100).toFixed(2)}% | ${a.venueLabel}`,
    )
    .join("\n");

  return `Portfolio rebalance for vault ${input.vaultAddress.slice(0, 10)}...
Risk Profile: ${input.riskProfile}
Portfolio Value: $${input.totalPortfolioValue}
Max allocation drift: ${(input.driftBps / 100).toFixed(2)}%

Allocation targets:
${lines}

Explain why this rebalance aligns with the ${input.riskProfile} profile, note key risk/yield trade-offs, and end with a confidence score (0-100).`;
}

function buildFallbackText(input: ReasoningInput): string {
  const driftPct = (input.driftBps / 100).toFixed(2);
  const top = [...input.currentAllocation].sort((a, b) => b.apyBps - a.apyBps)[0];
  return (
    `Autonomous rebalance triggered for ${input.riskProfile} profile. Allocation drift of ${driftPct}% exceeded threshold. ` +
    `Realigning to risk-adjusted target weights. ` +
    (top
      ? `Highest yielding position: ${top.symbol} at ${(top.apyBps / 100).toFixed(2)}% APY via ${top.venueLabel}. `
      : "") +
    `Decision generated by Equinox autonomous agent on Mantle Sepolia.`
  );
}

function buildFallback(input: ReasoningInput, model: string): ReasoningOutput {
  return {
    text: buildFallbackText(input),
    confidence: 70,
    payload: { ...input, model, timestamp: Date.now() },
  };
}
